### ISSUE TITLE
BUG: Pipeline Invocation Service ArgoCD template missing helm.values parameter

### ISSUE THREAD

**Issue by csun-cpointe** [boozallen/aissemble#491]
## Description
When setting the `-deploy/src/main/resources/apps/pipeline-invocation-service/values-dev.yaml`, the values can't be applied if deploying the app via ArgoCD because the missing `helm.values` parameters in the ArgoCD pipeline-invocation-service helm templates.

**Note:**
The fix should also include the migration script to ensure that the `pipeline-invocation-service` ArgoCD helm template add the  `helm.values` parameters after upgrade to version `1.11.0`

## Steps to Reproduce
1. Create a downstream project with baseline version 1.11.0-SNAPSHOT (**Note: the <<github_username>> in the following command must replaced with the actual value**)
```
mvn archetype:generate -DarchetypeGroupId=com.boozallen.aissemble \
                       -DarchetypeArtifactId=foundation-archetype \
                       -DarchetypeVersion=1.11.0-SNAPSHOT \
                       -DgroupId=org.test \
                       -DartifactId=verify-invocation-service \
                       -DprojectGitUrl=https://github.com/<<github_username>>/verify-invocation-service.git \
                       -DprojectName="Test Pipeline Invocation" \
&& cd verify-invocation-service
```
2. Add [SparkPipeline.json](https://github.com/user-attachments/files/17925376/SparkPipeline.json) to the verify-invocation-service-pipeline-models/src/main/resources/pipelines directory
3. Run mvn clean install until all the manual actions are complete
4. Run `mvn clean install -Dmaven.build.cache.skipCache` once to get any remaining manual actions
5. Config apps:
  - **Configuration-store:** delete the `verify-invocation-service-deploy/src/main/resources/templates/configuration-store.yaml` to skip the configuration-store configuration
  - **Pipeline Invocation Service:**: replace the content in the `-deploy/src/main/resources/apps/pipeline-invocation-service/values-dev.yaml` with below content
      ```
        aissemble-pipeline-invocation-chart:
          aissemble-quarkus-chart:
            image:
              imagePullPolicy: IfNotPresent
            service:
              type: NodePort
              ports:
                - name: "invocation-rest"
                  port: 8080
                  targetPort: 8080
                  nodePort: 30004
                - name: "quarkus-managed"
                  port: 9001
                  targetPort: 9000
            ingress:
              enabled: false
      ```

6. Create a repo for the project created 
   - Create a new verify-invocation-service repository from the `https://github.com/<<username>>?tab=repositories` (Note: replace the <<username>> with your GitHub user name
   - at the verify-invocation-service root directory run below commands
       -  `git init `
       -  `git add .`
       -  `git commit -m "init verify-invocation-service base"`
       -  `git branch -M main`
       -  `git remote add origin git@github.com:<username>/verify-invocation-service.git`
       -  `git push -u origin main`
    
7. Local deployment
   - At the project root directory, run `chmod +x deploy.sh`
   - Run `./deploy.sh up`
   - Wait until pipeline invocation service is in healthy status

## Expected Behavior

- Verify pipeline invocation service 
   Open the Pipeline Invocation Service [Service UI](http://localhost:30080/applications/argocd/pipeline-invocation-service?view=tree&node=%2FService%2Fverify-invocation-service%2Fpipeline-invocation-service%2F0&resource=), under `Live Manifest` tab, verify the port for the `invocation-rest` port is `30004`. e.g.: 
   ```
    ports:
      - name: invocation-rest
        nodePort: 30004
        port: 8080
        protocol: TCP
        targetPort: 8080
   ```

## Actual Behavior
Open the Pipeline Invocation Service [Service UI](http://localhost:30080/applications/argocd/pipeline-invocation-service?view=tree&node=%2FService%2Fverify-invocation-service%2Fpipeline-invocation-service%2F0&resource=), under `Live Manifest` tab, verify the port for the `invocation-rest` port is `30004`. e.g.: 

   ```
    ports:
        - name: invocation-rest
          port: 8085
          protocol: TCP
          targetPort: 8080
        - name: quarkus-mgmt
          port: 9001
          protocol: TCP
          targetPort: 9000
   ```

## Test Steps:
- Follow **the Steps to Reproduce** and verify the behavior matches the **Expected Behavior**
- For the upgrade:
   Create a downstream project with baseline version 1.10.0
   ```
     mvn archetype:generate -DarchetypeGroupId=com.boozallen.aissemble \
                       -DarchetypeArtifactId=foundation-archetype \
                       -DarchetypeVersion=1.10.0 \
                       -DgroupId=org.test \
                       -DartifactId=verify-migration \
                       -DprojectGitUrl=test.url \
                       -DprojectName="Test Pipeline Invocation Template Migration" \
     && cd verify-migration
   ```
- Follow the Step 2, 3 & 4
- Update baseline version to `1.11.0-SNAPSHOT` in both root pom.xml and Tiltfile
- Run `mvn org.technologybrewery.baton:baton-maven-plugin:baton-migrate`
- Verify the `verify-migration-deploy/src/main/resources/templates/pipeline-invocation-service.yaml` contains below content
   ```

        {{ if .Values.spec.helm.valueFiles }}
        helm:
          valueFiles:
            {{- range .Values.spec.helm.valueFiles }}
            - {{ . }}
            {{- end }}
        {{ end }}
   ```

## Additional Context
- Log output
- Screenshots (if applicable)
- Solution Baseline Version
- Environment details (local, cloud, Azure, AWS, etc.)
