### ISSUE TITLE
Feature: Support Configuration Store values to use properties to inject values

### ISSUE THREAD

**Issue by jaebchoi** [boozallen/aissemble#533]
## Description
The way we configured Configstore properties file seems to be more specific to one application and specifying volumePathOnNode for config store may be complicated on different machines (especially WSL).

We need additional ways to be more suitable across all machines and be able to abstract out properties so that we can reuse properties across different applications (not just spark-infrastructure). 

## Definition Of Done
- [x] Rename spark-infrastructure.properties to spark.properties
- [x] Support of updating configuration-store values file to add baseproperties with filename associated with properties key/values pair
```
  name: configuration-store-config
  baseConfigFiles:
    spark.properties: |-
      metastore.db.username=hive
      metastore.db.password=hive
  envConfigFiles:
    spark.properties: |-
      metastore.db.username=hive
      metastore.db.password=hive

```
- [x] update to support Configuration store logic to use properties pattern in addition to configurationVolume
- [x] Update README and antora doc of configuration Store based on this change.
- [x] Make sure configuration store can still work in local ArgoCD and can inject configurations correctly.

## Test Strategy/Script

- Pull `test533-with-deploy-script` branch (This includes  deploy script in feature/path2production-alignment for easily testing since this feature uses mutation webhook )
- Run mvn clean install

- Create a downstream project with baseline version 1.11.0-SNAPSHOT
```
mvn archetype:generate -U -DarchetypeGroupId=com.boozallen.aissemble \
  -DarchetypeArtifactId=foundation-archetype \
  -DarchetypeVersion=1.11.0-SNAPSHOT \
  -DgroupId=com.test \
  -DartifactId=test-533 \
  -DprojectGitUrl=https://github.com/{your-github-username}/test-533 \
  -DprojectName=test-533 \
  && cd test-533 
```

Replace {your-github-username} with your github username

- Add the [SparkPipeline.json](https://github.com/user-attachments/files/16781488/SparkPipeline.json) file to the test-533-pipeline-models/src/main/resources/pipelines directory
- Run mvn clean install until all the manual actions are complete
- Once the manual actions are complete, run `mvn clean install -Dmaven.build.cache.skipCache=true` once to get any remaining manual actions
- Modify `-deploy/src/main/resources/apps/spark-infrastructure/Charts.yaml' update following
```
  - name: aissemble-hive-metastore-service-chart
    version: 1.11.0-SNAPSHOT
    repository: oci://ghcr.io/jaebchoi
```
(Reason for this change is that we haven't merged [feature universal config integration](https://github.com/boozallen/aissemble/tree/feature/universal-config-integration) yet due to path2production work) 

- Modify configuration store values.yaml
   - in the `-deploy/src/main/resources/apps/spark-infrastructure/values.yaml' update configMap: to be following 
```
  configMap:
    configStore: enabled
    metastoreServiceConfig:
      properties:
        - name: javax.jdo.option.ConnectionUserName
          value: $getConfigValue(groupName=spark;propertyName=metastore.db.username)
          description: Username to use against metastore database
        - name: javax.jdo.option.ConnectionPassword
          value: hive
          description: Password to use against metastore database
        - name: metastore.warehouse.dir
          value: s3a://spark-infrastructure/warehouse
        - name: fs.s3a.endpoint
          value: http://s3-local:4566
        - name: fs.s3a.path.style.access
          value: true
```

- Create a repo for the project created 
   - create a new test-533 repository from the github website
   - at the test-533 root directory run below commands
   -  `git init `
   -  `git add .`
   -   `git commit -m "init test-533 base"`
   -  `git branch -M main`
   -  `git remote add origin https://github.com/<username>/<repo_name>.git`
   -  `git push -u origin main`

- on the root of your downstream project

- make deploy script executable permission
`chmod +x deploy.sh `

- change port fowarding  of argocd-server to 30080
i.e. go to Rancher desktop-> Click Port fowarding on left section
NOTE: we’re port forwarding to avoid bug with NodePort in RD on ARM Mac

- Run following to stand up argoCD
`./deploy.sh up`

- Go to localhost:30080 
- In Argo CD, Go to spark-infrastructure and make sure config store correctly injects  username with `hive`

![Image](https://github.com/user-attachments/assets/eee6702a-e367-493f-a044-fe15ad9a1c04)
![Image](https://github.com/user-attachments/assets/04649830-b4b2-47be-855c-14ab1acdc07f)

## References/Additional Context
Add any other context, links, or screenshots about the feature request here.
