### ISSUE TITLE
Feature: Ensure helm charts allow resource specification

### ISSUE THREAD

**Issue by peter-mcclonski** [boozallen/aissemble#546]
## Description
At this time, resource allocations cannot be specified for any `aissemble-quarkus`-based helm chart.  This presents challenges for a production deployment.  All helm charts managed by aissemble should allow the setting of resource requests and limits for all containers.

## DOD
Acceptance criteria required to realize the requested feature
- [x] Allow for resource specification for aissemble-spark-history, assemble-quarkus, and assemble-hive-metastore-service charts
- [x] specify resources, requests, and limits as part of the deployment template
- [x] create Helm unit tests to validate functionality
- [x] update README with new configuration options

## Test Strategy/Script (OTS)
- **OTS Only:**
  -  Build the three helm charts locally
      ```
      mvn clean install -pl :aissemble-spark-history-chart,:aissemble-quarkus-chart,:aissemble-hive-metastore-service-chart -Dmaven.build.cache.skipCache
      ```
- In the aiSSEMBLE root directory, create a file `myvalues.yaml` with the following content:
    ```yaml
    deployment:
      resources:
        requests:
          memory: 300Mi
          cpu: 100m
        limits:
          memory: 500Mi
          cpu: 200m
    ```
- Install the three charts passing in `myvalues.yaml`:
  - **OTS:**
      ```
      helm install aissemble-spark-history extensions/extensions-helm/extensions-helm-spark-infrastructure/aissemble-spark-history-chart/target/helm/repo/aissemble-spark-history-chart-1.11.0-SNAPSHOT.tgz --values myvalues.yaml
      helm install aissemble-quarkus extensions/extensions-helm/aissemble-quarkus-chart/target/helm/repo/aissemble-quarkus-chart-1.11.0-SNAPSHOT.tgz --values myvalues.yaml
      helm install aissemble-hive-metastore-service extensions/extensions-helm/extensions-helm-spark-infrastructure/aissemble-hive-metastore-service-chart/target/helm/repo/aissemble-hive-metastore-service-chart-1.11.0-SNAPSHOT.tgz --values myvalues.yaml
      ```
  - **Regular:**
      ```
      helm install aissemble-spark-history oci://ghcr.io/boozallen/aissemble-spark-history-chart --version 1.11.0-SNAPSHOT --values myvalues.yaml
      helm install aissemble-quarkus oci://ghcr.io/boozallen/aissemble-quarkus-chart --version 1.11.0-SNAPSHOT --values myvalues.yaml
      helm install aissemble-hive-metastore-service oci://ghcr.io/boozallen/aissemble-hive-metastore-service-chart --version 1.11.0-SNAPSHOT --values myvalues.yaml
      ```
- Check that the resources have been specified to match values in `myvalues.yaml`
    - Get each of the three pod names using `kubectl get pods`
    - For each pod name, get the pod yaml using `kubectl get pod <POD_NAME> -o yaml`
      - **Note**: skip the `hive-metastore-db-0` pod
    - Verify the following values are under `spec.containers.resources`:
      ```
      spec:
        ...
        containers:
          ...
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 300Mi
      ```
- Clean-up: delete `myvalues.yaml` and uninstall the charts
    ```
    helm uninstall aissemble-spark-history
    helm uninstall aissemble-quarkus
    helm uninstall aissemble-hive-metastore-service
    ```
