### ISSUE TITLE
As a consumer of the spark-history v2 helm chart, I want to be able to specify node affinities and tolerations.

### ISSUE THREAD

**Issue by peter-mcclonski** [boozallen/aissemble#96]
# Background
The recently created Spark History helm chart does not currently include support for specifying node affinities nor tolerations.  In order to grant greater deployment control to downstream projects, we should add this support.

# Definition of Done

- [x]  update helm chart to make node affinities and tolerations configurable
- [x] update unit test for yaml changes.
- [x] spark downstream project can be built successfully.
- [x] add read me to show node affinities and tolerations are supported.
- [x]  updated node affinities and tolerations took effect in spark history pods.

# Test Instructions
- pull in latest dev branch of aissemble
- make sure build is successful
- Build downstream project using following command:
```
 mvn archetype:generate -U -DarchetypeGroupId=com.boozallen.aissemble \
  -DarchetypeArtifactId=foundation-archetype \
  -DarchetypeVersion=1.10.0-SNAPSHOT\
  -DgroupId=com.boozallen.aissemble.test \
  -DartifactId=issue-96\
  -DprojectGitUrl=git.example.com/issue-96 \
  -DprojectName=“issue-96”
```
- cd into downstream project.
- Add a spark pipeline with a training step to an aissemble project by saving attached json into
[SparkPipeline.json](https://github.com/user-attachments/files/17263573/SparkPipeline.json)

`{downstream-project}/{downstream-project}-pipeline-models/src/main/resources/pipelines`
- Run ./mvn clean install and follow manual actions.
- under {downstream-project}-deploy/src/main/resources/apps/spark-infrastructure/values.yaml, update tolerances and affinity as below for aissemble-spark-history-chart screenshot

```
  deployment:
    tolerations:
        - key: "node.kubernetes.io/not-ready-test"
          operator: "Exists"
          effect: "NoSchedule"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
```

<img width="1202" alt="Screenshot 2024-10-04 at 11 32 40 AM" src="https://github.com/user-attachments/assets/44065b96-b19d-406d-9439-db97d5980821">

- Run mvn clean install once more
- Deploy the project with tilt up
- click on spark-infrastructure-shs
- you can get pod name here
![Screenshot 2024-10-04 at 4 45 26 PM](https://github.com/user-attachments/assets/315fbef6-13ac-46bd-a651-8676a56b407a)

- make sure spark-history have updated node affinities and tolerations
 NOTE: you can do this by running kubectl get pods {spark-history-pod-name} -o json
and inspect node affinity and tolerations are added in the json file.

NOTE: toleration will have default values below so it is normal to have two in place. 

```
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/not-ready",
                "operator": "Exists",
                "tolerationSeconds": 300
            },
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/unreachable",
                "operator": "Exists",
                "tolerationSeconds": 300
            }

```
